<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminPanel.aspx.cs" Inherits="Login_AdminPanel" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

 <html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
    <form id="form1" runat="server">
    WELCOME: <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label> / <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
   <div class="container">
      <div class="wrapper">
        <div class="title"><span>UPLOAD PRODUCT</span></div>
        <form1 action="#">
        <asp:Label ID="Label_MSG" runat="server" Text=""></asp:Label>
          <div class="row">
            <i class="fas fa-user"></i>
            <asp:TextBox ID="TextBox1_Catg" runat="server" placeholder="Category" ></asp:TextBox>
            
          </div>
          <div class="row">
            <i class="fas fa-lock"></i>
            <asp:TextBox ID="TextBox2_Name" runat="server" placeholder="Name" ></asp:TextBox>
          </div>

            <div class="row">
            <i class="fas fa-lock"></i>
            <asp:TextBox ID="TextBox3_Dprice" runat="server" placeholder="Discounted Price" ></asp:TextBox>
          </div>

            <div class="row">
            <i class="fas fa-lock"></i>
            <asp:TextBox ID="TextBox4_Oprice" runat="server" placeholder="Original Price" ></asp:TextBox>
          </div>


          
            <div class="row">
            <i class="fas fa-lock"></i>
           <asp:FileUpload ID="FileUpload1" runat="server"></asp:FileUpload>
          </div>



           
          <div class="row button">
          <asp:Button ID="Button1" runat="server" Text="UPLOAD PRODUCT" onclick="Button1_Click"></asp:Button>
            
          </div>
          <div class="signup-link"> <a href="../Default.aspx">User Front page</a></div>
        </form1>
      </div>
    </div>
    <asp:TextBox ID="TextBox_Autogen" runat="server" Visible="false"></asp:TextBox>


    <br /><br /><br /><br /><br />


    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" BackColor="White" DataKeyNames="id,photo" 
                BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                HorizontalAlign="Center" Width="100%" onrowdeleting="GridView1_RowDeleting" 
                    >
                    <RowStyle BackColor="White" ForeColor="#003399" HorizontalAlign="Center" />
                    <Columns>
                        <asp:TemplateField HeaderText="ID">
                             
                            <ItemTemplate>
                                <asp:Label ID="LabelA" runat="server" Text='<%# Bind("id") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                     
                        
                                                 
                        
                        <asp:TemplateField HeaderText="Heading">
                             
                            <ItemTemplate>
                                <asp:Label ID="LabelB" runat="server" Text='<%# Bind("catg") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                         <asp:TemplateField HeaderText="Year">
                             
                            <ItemTemplate>
                                <asp:Label ID="LabelCKl" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>


                        <asp:TemplateField HeaderText="Month">
                             
                            <ItemTemplate>
                                <asp:Label ID="LabelCKsl" runat="server" Text='<%# Bind("dprice") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Rels.Date">
                             
                            <ItemTemplate>
                                <asp:Label ID="LabelC" runat="server" Text='<%# Bind("oprice") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Photo">
                             
                            <ItemTemplate>
                           
                           <asp:Image ID="Image1Ac" runat="server"  ImageUrl='<%# Bind("photo") %>'  Width="80px"/>
                                
                            </ItemTemplate>
                        </asp:TemplateField>

                           
                      


                       
                        
                        
                    </Columns>
                    <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                    <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                    <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                </asp:GridView>



    </form>
</body>
</html>
